# Generated by Django 2.2 on 2019-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deckname', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField()),
                ('price', models.CharField(choices=[('B', 'Budget Standard Deck'), ('M', 'Average Cost Standard Deck'), ('E', 'Expensive Standart Deck'), ('U', 'Unknown / Yet to be Determined')], default='U', max_length=1)),
            ],
        ),
    ]
