# Generated by Django 2.2 on 2019-10-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teardecks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='img_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
