# Generated by Django 2.2 on 2019-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teardecks', '0002_deck_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(blank=True, max_length=50)),
                ('manacost', models.CharField(blank=True, max_length=50)),
                ('set_name', models.CharField(blank=True, max_length=50)),
                ('card_price', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
