# Generated by Django 2.2 on 2019-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teardecks', '0003_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='img_url',
        ),
        migrations.AddField(
            model_name='deck',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='deck_images'),
        ),
    ]
