# Generated by Django 2.2 on 2019-10-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teardecks', '0004_auto_20191002_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teardecks.Deck', verbose_name='User'),
            preserve_default=False,
        ),
    ]
