# Generated by Django 2.2 on 2019-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teardecks', '0006_auto_20191003_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
